package com.tao.fda.model;

public enum RiskRuleId {

	R1_CARD_TESTING_VELOCITY, R2_IP_CLUSTERING, R3_DECLINE_SPIKES, R4_IMPOSSIBLE_TRAVEL, R5_LAST_AMOUNT_SPIKE,
	R6_CROSS_BORDER_JUMP, R7_NIGHT_TIME_RISK, R8_HIGH_VALUE_BLOCK, R9_BLACKLIST_CHECK

}
